### PR TITLE
fix: merge base to main

### LINKED ISSUE #117: merge phase-3 branch into `main`

### PR DESCRIPTION
**Pull request by SebastianElvis**
Resolves #117 

This PR merges base branch to main

### CODE REVIEW

File: itest/containers/config.go [hunk 1]
```diff
@@ -27,6 +28,8 @@ func NewImageConfig(t *testing.T) ImageConfig {
 	babylondVersion, err := testutil.GetBabylonVersion()
 	require.NoError(t, err)
 
+	babylondVersion = "latest" // TODO: change back
```
Comment (Lazar955) [inline itest/containers/config.go:31]: rm this

**Review by Lazar955 — APPROVED** [review]

**Review by KonradStaniec — APPROVED** [review]
